### ISSUE TITLE
[1.20.1]当用jei查看create注液配方时崩溃

### ISSUE THREAD

**Issue by SolarMoonQAQ** [Zoshsgahdnkc/kitchenkarrot#16]
mod列表： create-1.20.1-0.5.1.e.jar， jei-1.20.1-forge-15.2.0.27，kitchenkarrot-1.20.1-0.5.0
版本：kitchenkarrot-1.20.1-0.5.0
复现方法：1.装载如上三个模组，2.对着注液器按U键查看其配方，3.往后翻几页，4.崩溃
崩溃报告：
[crash-2023-10-28_07.57.06-client.txt](https://github.com/Zoshsgahdnkc/kitchenkarrot/files/13193962/crash-2023-10-28_07.57.06-client.txt)

**Comment by Zoshsgahdnkc** [comment]
将在下个版本移除相关配方解决问题
