### ISSUE TITLE
移植到1.19.4

### ISSUE THREAD

**Issue by xdedss** [Zoshsgahdnkc/kitchenkarrot#20]
很棒的模组，感谢制作者

这里简单地做了一下1.19.4的移植[xdedss/kitchenkarrot](https://github.com/xdedss/kitchenkarrot)

**Comment by Zoshsgahdnkc** [comment]
辛苦了，需要在网站上发布并加为作者吗

**Comment by xdedss** [comment]
发布一下吧，让大家知道有1.19.4版本可以用）

另外可以考虑从1.20分出来一个1.19.4的branch，我提一个PR合进来（因为是从1.20的基础上改的，合进现有的哪个branch好像都不太合适）
